[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@uniswap/v4-core/=/Users/olivertipton/Desktop/Eigen Games Hackathon/deployer_and_tester/lib/v4-core/",
    "@uniswap/v4-periphery/=/Users/olivertipton/Desktop/Eigen Games Hackathon/deployer_and_tester/lib/v4-periphery/",
    "v4-core/=/Users/olivertipton/Desktop/Eigen Games Hackathon/deployer_and_tester/lib/v4-core/",
    "v4-periphery/=/Users/olivertipton/Desktop/Eigen Games Hackathon/deployer_and_tester/lib/v4-periphery/",
    "forge-std/=/Users/olivertipton/Desktop/Eigen Games Hackathon/deployer_and_tester/lib/forge-std/src/"
    ,
    "solmate/=lib/solmate/"
]
solc = "0.8.26" 